#!/bin/bash

dockerFolder="/usr/share/server/docker"

git clone "https://github.com/afercin/CrossGameWP.git" "${dockerFolder}/web"
/usr/local/bin/docker-compose -f "${dockerFolder}/docker-compose.yml" up -d 2>&1