#!/bin/bash
#Instalar librerías de python
pythonDependencies=("screeninfo" "ds4drv" "pygame" "pynput" "playsound" "selenium")

for dependency in ${pythonDependencies[@]}; do
    echo "Installing $dependency"
    pip install $dependency
done 