#!/bin/bash

echo "Creating PS1 memcards folder soft link..."
ln -s "/rpi/content/memcards/ps1" "/home/crossgame/.local/share/duckstation/memcards"

echo "Creating PSP memcards folder soft link..."
ln -s "/rpi/content/memcards/psp" "/home/crossgame/.config/ppsspp/PSP/SAVEDATA"

echo "Creating N64 memcards folder soft link..."
mkdir -p "/home/crossgame/.local/share/mupen64plus/save"
ln -s "/rpi/content/memcards/n64" "/home/crossgame/.local/share/mupen64plus/save"
