version: "3.3"

services:
    packager:
        container_name: crossgame.packager.raspbian
        image: crossgame.packager.raspbian:buster
        build: .
        working_dir: /src
        volumes:
         - .:/src
        command: bash -c "
            rm -rf /src/release/*
            && /src/build.sh"
    app-compiler:
        container_name: crossgame.compiler
        image: electronuserland/builder
        working_dir: /app
        volumes:
         - ../CrossGameApp:/app
         - ./release:/release
        command: bash -c "
            npm run dist_armhf
            && cp ./dist/crossgame*armv7l.deb /release
            && rm -r ./dist ./release"