#!/bin/bash

#establecer contraseña root
sudo usermod --password $(echo patata123 | openssl passwd -1 -stdin) root

#Iniciar equipo sin gui
systemctl set-default multi-user

#Deshabilitar apagado automático
systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

if [[ ! -d "/etc/productConf" ]]; then
    sudo mkdir "/etc/productConf"
    sudo chmod 777 "/etc/productConf"
fi

#Añadir privilegios de ejecución para los scripts
chmod 777 "/usr/bin/restartx"
chmod 777 "/usr/bin/swapmode"
chmod 777 "/usr/bin/automount"
chmod 777 "/usr/bin/redirectaudio"
chmod 777 "/usr/bin/restorepoint"

#Establecer zona horaria
sudo timedatectl set-timezone Europe/Madrid 

#Crear carpeta para punto de montaje del HDD
mkdir "/mnt/hdd"
chown crossgame:crossgame "/mnt/hdd"

#Crear carpeta para logs
sudo mkdir -p "/var/log/product"
sudo chmod 777 "/var/log/product"

#Habilitar servicio de automontage
systemctl daemon-reload
systemctl enable automount.service
systemctl start automount.service