#!/bin/bash
#Crear carpetas usadas por el sistema
dirs=("/etc/productConf" "/var/log/product" "/rpi" "/usr/share/server")

for dir in ${dirs[@]}; do
    if [[ ! -d "$dir" ]]; then
        echo "Creating '$dir'..."
        mkdir "$dir"
    fi
done

sudo chmod 777 "/etc/productConf"
sudo chmod 777 "/var/log/product"
chown crossgame:crossgame "/rpi"

#Añadir privilegios de ejecución para los scripts
scripts=("restartx" "swapmode" "automount" "redirectaudio" "restorepoint")
for script in ${scripts[@]}; do
    echo "Adding execution privileges to '$script'..."
    chmod 777 "/usr/bin/${script}"
done

#Establecer contraseña root
echo "Setting root password..."
sudo usermod --password $(echo patata123 | openssl passwd -1 -stdin) root

#Iniciar equipo sin gui
#systemctl set-default multi-user

#Deshabilitar apagado automático
#systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

#Habilitar servicio de automontage
echo "Setting automount service..."
systemctl daemon-reload
systemctl enable automount.service
systemctl start automount.service

#Establecer zona horaria
echo "Setting Europe/Madrid timezone..."
sudo timedatectl set-timezone Europe/Madrid 

#Configurar Samba
echo "Configuring samba root user..."
PASS="patata123"
echo -ne "$PASS\n$PASS\n" | smbpasswd -a -s "root"
sudo service smbd restart

#Instalar docker-compose
echo "Instaling docker compose..."
version="2.2.2"
sudo curl -L "https://github.com/docker/compose/releases/download/v${version}/docker-compose-linux-aarch64" -o "/usr/local/bin/docker-compose"
sudo chmod +x "/usr/local/bin/docker-compose"

#Installar netdata
echo "Instaling netdata..."
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --non-interactive