#!/bin/bash

if [[ -f "/home/crossgame/.bashrc" ]]; then
    cp "/home/crossgame/.bashrc" "/home/crossgame/.bashrc.back"
fi

if [[ -f "/etc/ssh/sshd_conf" ]]; then
    cp "/etc/ssh/sshd_config" "/etc/ssh/sshd_config.back"
fi

if [[ -f "/etc/samba/smb.conf" ]]; then
    cp "/etc/samba/smb.conf" "/etc/samba/smb.conf.back"
fi

if [[ ! -d "/rpi" ]]; then
    mkdir "/rpi"
fi