#!/bin/bash
#Crear carpetas usadas por el sistema
dirs=("/etc/productConf" "/var/log/product" "/rpi" "/usr/share/server")

for dir in ${dirs[@]}; do
    if [[ ! -d "$dir" ]]; then
        echo "Creating '$dir'..."
        mkdir "$dir"
    fi
done

sudo chmod 777 "/etc/productConf"
sudo chmod 777 "/var/log/product"
sudo chown crossgame:adrix "/rpi"

#Añadir privilegios de ejecución para los scripts
scripts=("restartx" "automount" "restorepoint")
for script in ${scripts[@]}; do
    echo "Adding execution privileges to '$script'..."
    sudo chmod 777 "/usr/bin/${script}"
done

#Establecer contraseña root
echo "Setting root password..."
sudo usermod --password $(echo patata123 | openssl passwd -1 -stdin) root

#Iniciar equipo sin gui
sudo systemctl set-default multi-user

#Deshabilitar apagado automático
#systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

#Habilitar servicios
echo "Setting up automount service..."
v systemctl daemon-reload
sudo systemctl enable automount.service
sudo systemctl start automount.service

echo "Setting up rc-local service..."
chmod u+x "/etc/rc.local"
sudo systemctl enable rc-local
sudo systemctl start rc-local

#Establecer zona horaria
echo "Setting Europe/Madrid timezone..."
sudo timedatectl set-timezone Europe/Madrid 

#Configurar Samba
echo "Configuring samba root user..."
PASS="patata123"
echo -ne "$PASS\n$PASS\n" | smbpasswd -a -s "root"
sudo service smbd restart
sudo systemctl disable smbd.service

# #Preparar repositorio para instalar docker
# echo "Adding docker repository..."

# if [[ ! -f "/usr/share/keyrings/docker-archive-keyring.gpg" ]]; then
#     rm "/usr/share/keyrings/docker-archive-keyring.gpg"
#     curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | sudo gpg --dearmor --always-trust -o "/usr/share/keyrings/docker-archive-keyring.gpg" 
#     echo \
#     "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
#     $(lsb_release -cs) stable" | sudo tee "/etc/apt/sources.list.d/docker.list" > /dev/null
#     sudo apt-get update
# else
#     echo "Docker repository is already added."
# fi

# #Instalar docker-compose
# echo "Installing docker compose..."
# version="2.2.2"
# sudo curl -L "https://github.com/docker/compose/releases/download/v${version}/docker-compose-linux-aarch64" -o "/usr/local/bin/docker-compose"
# sudo chmod +x "/usr/local/bin/docker-compose"

#Installar netdata
echo "Installing netdata..."
if [[ ! -d "/var/lib/netdata" ]]; then
    bash <(curl -Ss https://my-netdata.io/kickstart.sh) --non-interactive
else
    echo "Netdata is already installed"
fi