version: "3.3"

services:
    packager:
        container_name: crossgame.packager.raspbian
        image: crossgame.packager.raspbian:buster
        build: .
        working_dir: /scripts
        volumes:
         - ../release:/release
         - ../confBase:/confBase
         - ../emulators:/emulators
         - ../plymouth:/plymouth
         - ../utils:/utils
        command: bash -c "
            rm -r /release/* || true
            && cd /emulators
            && dpkg-buildpackage -b -us -uc
            && cd /confBase
            && dpkg-buildpackage -b -us -uc
            && cd /utils
            && dpkg-buildpackage -b -us -uc
            && cd /plymouth
            && dpkg-buildpackage -b -us -uc
            && mv /*.deb /release"
    app-compiler:
        container_name: crossgame.compiler
        image: electronuserland/builder
        working_dir: /app
        volumes:
         - ../../CrossGameApp:/app
         - ../release:/release
        command: bash -c "
            npm run dist_armhf
            && cp ./dist/crossgame*armv7l.deb /release
            && rm -r ./dist ./release"