version: "3.3"

services:
    packager:
        container_name: crossgame.packager.ubuntu
        image: crossgame.packager.ubuntu:20.04
        build: .
        working_dir: /scripts
        volumes:
         - ./scripts:/scripts
         - ../release:/release
         - ../.third-party:/third-party
         - ../crossGameConfBase:/crossGameConfBase
         - ../crossGameEmulators:/crossGameEmulators
         - ../crossGamePlymouth:/crossGamePlymouth
         - ../crossGameUtils:/crossGameUtils
        command: bash -c "
            rm -r /release/* || true
            && rm -r /crossGameEmulators/rpi/emulators || true
            && mkdir -p /crossGameEmulators/rpi/emulators
            && ./n64_build.sh
            && ./ps1_build.sh
            && ./psp_build.sh
            && ./build_packages.sh"
    app-compiler:
        container_name: crossgame.compiler
        image: electronuserland/builder
        working_dir: /app
        volumes:
         - ../../CrossGameApp:/app
         - ../release:/release
        command: bash -c "
            npm run dist_arm64
            && cp ./dist/crossgame*arm64.deb /release
            && rm -r ./dist ./release"