version: "3.3"

services:
    packager:
        container_name: crossgame.packager.ubuntu
        image: crossgame.packager.ubuntu:20.04
        build: .
        working_dir: /scripts
        volumes:
         - ../release:/release
         - ../confBase:/confBase
         - ../emulators:/emulators
         - ../crossGamePlymouth:/crossGamePlymouth
         - ../crossGameUtils:/crossGameUtils
        command: bash -c "
            rm -r /release/* || true
            && cd /confBase
            && dpkg-buildpackage -rfakeroot -b -us -uc
            && cd /emulators
            && dpkg-buildpackage -rfakeroot -b -us -uc"
    app-compiler:
        container_name: crossgame.compiler
        image: electronuserland/builder
        working_dir: /app
        volumes:
         - ../../CrossGameApp:/app
         - ../release:/release
        command: bash -c "
            npm run dist_arm64
            && cp ./dist/crossgame*arm64.deb /release
            && rm -r ./dist ./release"