version: "3.9"

services:
    packager:
        container_name: crossgame.packager
        build: .
        volumes:
         - ./scripts:/scripts
         - ../release:/release
         - ../.third-party:/third-party
         - ../crossGameEmulators:/crossGameEmulators
         - ../crossGameServer:/crossGameServer
        command: bash -c "
            rm /release/* || true &&
            /scripts/emulators_compile.sh &&
            /scripts/build_packages.sh"
    app-compiler:
        container_name: crossgame.compiler
        image: electronuserland/builder
        working_dir: /app
        volumes:
         - /home/afercin/dev/CrossGameApp:/app
         - ../release:/release
        command: bash -c "
            npm run dist_arm64 &&
            cp ./dist/crossgame*arm64.deb /release"