version: "3.9"

services:
    packager:
        container_name: crossgame.packager
        build: .
        working_dir: /scripts
        volumes:
         - ./scripts:/scripts
         - ../release:/release
         - ../.third-party:/third-party
         - ../crossGameConfBase:/crossGameConfBase
         - ../crossGameEmulators:/crossGameEmulators
         - ../crossGamePlymouth:/crossGamePlymouth
         - ../crossGameUtils:/crossGameUtils
        command: bash -c "
            rm -r /release/* || true &&
            ./n64_build.sh &&
            ./ps1_build.sh &&
            ./psp_build.sh &&
            ./build_packages.sh"
    app-compiler:
        container_name: crossgame.compiler
        image: electronuserland/builder
        working_dir: /app
        volumes:
         - /home/afercin/dev/CrossGameApp:/app
         - ../release:/release
        command: bash -c "
            npm run dist_arm64 &&
            cp ./dist/crossgame*arm64.deb /release"