#!/bin/bash

[[ -d "/tmp/emulators" ]] && rm -r "/tmp/emulators"
[[ ! -d "/usr/share/server/emulators" ]] && mkdir -p "/usr/share/server/emulators"

mkdir "/tmp/emulators"

emulators="/usr/share/server/emulators"
tmpfolder="/tmp/emulators"

#Compiling psx emulator
if [[ ! -d "$emulators/duckstation" ]]; then
    git clone "https://github.com/stenzek/duckstation.git" -b dev "$tmpfolder/duckstation"
    mkdir "$tmpfolder/duckstation/build/"
    cd "$tmpfolder/duckstation/build"
    cmake -DCMAKE_BUILD_TYPE=Release -GNinja "$tmpfolder/duckstation/"
    ninja 
    mv "$tmpfolder/duckstation/build/bin" "$emulators/duckstation"
    ln -s "/mnt/rpi/memcards/ps1" "/home/crossgame/.local/share/duckstation/memcards"
fi

#Compiling ps2 emulator
if [[ ! -d "$emulators/play-" ]]; then
    git clone --recurse-submodules "https://github.com/jpd002/Play-.git" "$tmpfolder/play-"
    mkdir "$tmpfolder/play-/build/"
    cd "$tmpfolder/play-/build"
    sed -i "s/ OR TARGET_PLATFORM_UNIX_ARM OR TARGET_PLATFORM_UNIX_AARCH64//" "$tmpfolder/play-/deps/Framework/build_cmake/FrameworkOpenGl/CMakeLists.txt"
    cmake -G Ninja -DCMAKE_PREFIX_PATH=/opt/qt56/ "$tmpfolder/play-/"
    cmake --build "$tmpfolder/play-/build" --config Release
    mv "/$tmpfolder/play-/build/Source/ui_qt" "$emulators/play-"
fi

# Compiling psp emulator
if [[ ! -d "$emulators/ppsspp" ]]; then
    git clone --recurse-submodules "https://github.com/hrydgard/ppsspp.git" "$tmpfolder/ppsspp"
    mkdir "$tmpfolder/ppsspp/build/"
    cd "$tmpfolder/ppsspp/build/"
    cmake ..
    cmake -j 4 ..
    make install
    mkdir "$emulators/ppsspp"
    cp "$tmpfolder/ppsspp/build/PPSSPPSDL" "$emulators/ppsspp/"
    ln -s "/mnt/rpi/memcards/psp" "/home/crossgame/.config/ppsspp/PSP/SAVEDATA"
fi